#include "../Rulesets/BrainsBrainRuleSet.h"
#include "../Rulesets/DayAndNightRuleSet.h"
#include "../Rulesets/GameOfLifeRuleSet.h"
#include "../Rulesets/HighlifeRuleSet.h"
#include "../Rulesets/LifeWithoutDeathRuleSet.h"
#include "../Rulesets/SeedsRuleSet.h"